window.INVENTUR_ITEMS=[
["80191", "sonstige", "Stueck", "Bambusmatte groß 27×27cm", "Mành tre lớn 27×27cm", "Bamboo mat large 27×27cm", "เสื่อไม้ไผ่ใหญ่ 27×27ซม.", "大号竹卷帘 27×27cm"],
["99315", "sonstige", "Stueck", "Bambusmatte 24×24cm (SC)", "Mành tre 24×24cm", "Bamboo mat 24×24cm", "เสื่อไม้ไผ่ 24×24ซม.", "竹卷帘 24×24cm (SC)"],
["80024", "sauce", "Stueck", "Chilipulver Shichimi Togarashi", "Bột ớt Shichimi Togarashi", "Chili powder Shichimi Togarashi", "พริกป่น Shichimi Togarashi", "七味唐辛子辣椒粉"],
["98009", "sauce", "Stueck", "Chilisauce (4,5l Kanister)", "Sốt ớt (can 4,5l)", "Chili sauce (4.5l canister)", "ซอสพริก (แกลลอน 4.5ล.)", "辣椒酱（4.5升桶装）"],
["99143", "sonstige", "Stueck", "Essstäbchen Bambus 23cm", "Đũa tre 23cm", "Bamboo chopsticks 23cm", "ตะเกียบไม้ไผ่ 23ซม.", "竹筷 23cm"],
["80318", "sauce", "Stueck", "Furikake (Nori-Würzmischung)", "Furikake (gia vị rắc cơm)", "Furikake (rice seasoning)", "ฟุริคาเกะ (ผงโรยข้าว)", "香松（海苔调味料）"],
["80028", "tk", "Stueck", "Wakame getrocknet", "Rong wakame khô", "Dried wakame", "สาหร่ายวากาเมะแห้ง", "干裙带菜"],
["98044", "sauce", "KG", "Sesam schwarz geröstet (1kg)", "Mè đen rang (1kg)", "Black sesame roasted (1kg)", "งาดำคั่ว (1กก.)", "烤黑芝麻（1公斤）"],
["98043", "sauce", "KG", "Sesam weiß geröstet (1kg)", "Mè trắng rang (1kg)", "White sesame roasted (1kg)", "งาขาวคั่ว (1กก.)", "烤白芝麻（1公斤）"],
["98060", "reis", "Stueck", "Nori Gold halbe Blätter", "Nori Gold lá nửa", "Nori Gold half sheets", "สาหร่ายโนริ Gold แผ่นครึ่ง", "金牌海苔 半张"],
["98061", "reis", "Stueck", "Nori Gold ganze Blätter", "Nori Gold lá nguyên", "Nori Gold full sheets", "สาหร่ายโนริ Gold แผ่นเต็ม", "金牌海苔 整张"],
["99310", "reis", "Stueck", "Sushi Nori ganz (SC)", "Nori sushi lá nguyên", "Sushi Nori full (SC)", "โนริซูชิแผ่นเต็ม", "寿司海苔 整张 (SC)"],
["98101", "sauce", "Stueck", "Ingwer Gari eingelegt (1kg)", "Gừng Gari ngâm (1kg)", "Pickled ginger Gari (1kg)", "ขิงดอง Gari (1กก.)", "腌姜片 Gari（1公斤）"],
["80178", "gemuese", "Stueck", "Röstzwiebeln", "Hành phi", "Fried onions", "หอมเจียว", "炸洋葱酥"],
["80264", "reis", "Stueck", "Reispapier rund 22cm", "Bánh tráng tròn 22cm", "Rice paper round 22cm", "แผ่นแป้งข้าวกลม 22ซม.", "圆形米纸 22cm"],
["4939", "sauce", "Stueck", "Wasabi Paste", "Mù tạt Wasabi", "Wasabi paste", "วาซาบิ", "芥末酱"],
["80132", "sauce", "Stueck", "Mayo japanese style", "Sốt Mayo kiểu Nhật", "Japanese style mayo", "มาโยญี่ปุ่น", "日式蛋黄酱"],
["80127", "sauce", "Stueck", "Sesam-Sauce Goma Dare (1l)", "Sốt mè Goma Dare (1l)", "Sesame sauce Goma Dare (1l)", "ซอสงา Goma Dare (1ล.)", "芝麻酱 Goma Dare（1升）"],
["80267", "reis", "Stueck", "Reisnudeln 400g", "Bún gạo 400g", "Rice noodles 400g", "เส้นหมี่ข้าว 400ก.", "米粉 400克"],
["98019", "sauce", "Stueck", "Unagi-Sauce (Aalsauce, 1,8l)", "Sốt lươn Unagi (1,8l)", "Unagi sauce (eel, 1.8l)", "ซอสปลาไหล Unagi (1.8ล.)", "鳗鱼汁（1.8升）"],
["99309", "sauce", "Stueck", "Sushi Ingwer im Glas (SC)", "Gừng sushi lọ thủy tinh", "Sushi ginger in jar", "ขิงซูชิในขวด", "寿司姜片 玻璃罐装"],
["80020", "sauce", "Stueck", "Sesamöl 100% (1,8l)", "Dầu mè 100% (1,8l)", "Sesame oil 100% (1.8l)", "น้ำมันงา 100% (1.8ล.)", "纯芝麻油（1.8升）"],
["80316", "sauce", "Stueck", "Sushi-Su Marinade (10l)", "Giấm trộn cơm Sushi-Su (10l)", "Sushi-Su marinade (10l)", "น้ำส้มผสมข้าวซูชิ (10ล.)", "寿司醋调味汁（10升）"],
["80003", "reis", "KG", "Sushireis (Sack 10kg)", "Gạo sushi (bao 10kg)", "Sushi rice (10kg sack)", "ข้าวซูชิ (กระสอบ 10กก.)", "寿司米（10公斤袋装）"],
["4857", "tk", "Stueck", "Mochi Cheesecake 192g (TK)", "Mochi phô mai 192g (đông lạnh)", "Mochi cheesecake 192g (frozen)", "โมจิชีสเค้ก 192ก. (แช่แข็ง)", "芝士蛋糕大福 192克（冷冻）"],
["4854", "tk", "Stueck", "Mochi Kakao 192g (TK)", "Mochi ca cao 192g (đông lạnh)", "Mochi cocoa 192g (frozen)", "โมจิโกโก้ 192ก. (แช่แข็ง)", "可可大福 192克（冷冻）"],
["4852", "tk", "Stueck", "Mochi Kokosnuss 192g (TK)", "Mochi dừa 192g (đông lạnh)", "Mochi coconut 192g (frozen)", "โมจิมะพร้าว 192ก. (แช่แข็ง)", "椰子大福 192克（冷冻）"],
["4853", "tk", "Stueck", "Mochi Mango 192g (TK)", "Mochi xoài 192g (đông lạnh)", "Mochi mango 192g (frozen)", "โมจิมะม่วง 192ก. (แช่แข็ง)", "芒果大福 192克（冷冻）"],
["4858", "tk", "Stueck", "Mochi Vanille 192g (TK)", "Mochi vani 192g (đông lạnh)", "Mochi vanilla 192g (frozen)", "โมจิวานิลลา 192ก. (แช่แข็ง)", "香草大福 192克（冷冻）"],
["91580", "fisch", "Stueck", "Masago Orange 450g (TK)", "Trứng cá Masago cam 450g", "Masago orange 450g (frozen)", "ไข่ปลามาซาโกะส้ม 450ก.", "橙色飞鱼籽 450克（冷冻）"],
["1599", "tk", "KG", "Goma Wakame Salat (TK)", "Gỏi rong biển Goma Wakame", "Goma wakame salad (frozen)", "สลัดสาหร่ายโกมะวากาเมะ", "芝麻裙带菜沙拉（冷冻）"],
["4978", "tk", "Stueck", "Inariage Sojataschen 900g (TK)", "Túi đậu Inari 900g (đông lạnh)", "Inari tofu pockets 900g (frozen)", "เต้าหู้อินาริ 900ก. (แช่แข็ง)", "豆皮寿司袋 900克（冷冻）"],
["4807", "tk", "Stueck", "Edamame geschält 500g (TK)", "Đậu nành Edamame 500g (đông lạnh)", "Edamame peeled 500g (frozen)", "ถั่วแระเอดามาเมะ 500ก.", "去壳毛豆 500克（冷冻）"],
["4980", "fisch", "KG", "Surimi Maki Sticks 1kg (TK)", "Thanh cua Surimi 1kg (đông lạnh)", "Surimi sticks 1kg (frozen)", "ปูอัดซูริมิ 1กก. (แช่แข็ง)", "蟹肉棒 1公斤（冷冻）"],
["4912", "tk", "Stueck", "Gyoza Seafood 500g (TK)", "Gyoza hải sản 500g (đông lạnh)", "Gyoza seafood 500g (frozen)", "เกี๊ยวซ่าทะเล 500ก. (แช่แข็ง)", "海鲜饺子 500克（冷冻）"],
["4910", "tk", "Stueck", "Gyoza vegetarisch 500g (TK)", "Gyoza chay 500g (đông lạnh)", "Gyoza vegetarian 500g (frozen)", "เกี๊ยวซ่าเจ 500ก. (แช่แข็ง)", "素食饺子 500克（冷冻）"],
["4899", "tk", "Stueck", "Gebratene Nudeln mit Gemüse (TK)", "Mì xào rau (đông lạnh)", "Fried noodles with veg (frozen)", "บะหมี่ผัดผัก (แช่แข็ง)", "蔬菜炒面（冷冻）"],
["4985", "tk", "Stueck", "Tamago Ei-Omelett Block 600g (TK)", "Trứng cuộn Tamago 600g (đông lạnh)", "Tamago omelette block 600g (frozen)", "ไข่หวานทามาโกะ 600ก. (แช่แข็ง)", "玉子烧蛋卷 600克（冷冻）"],
["1114", "fisch", "Stueck", "Sushi Ebi 3L (gekochte Garnele)", "Tôm sushi Ebi 3L (đã luộc)", "Sushi ebi 3L (cooked shrimp)", "กุ้งซูชิเอบิ 3L (ต้มสุก)", "寿司虾 3L（熟虾）"],
["1110", "fisch", "Stueck", "Garnelen für Gunkan", "Tôm cho Gunkan", "Shrimp for gunkan", "กุ้งสำหรับกุนคัง", "军舰卷用虾"],
["2850", "fisch", "KG", "Thunfisch Big Eye Saku (TK, kg)", "Cá ngừ Big Eye Saku (đông lạnh)", "Tuna Big Eye Saku (frozen)", "ทูน่า Big Eye Saku (แช่แข็ง)", "大目金枪鱼柳（冷冻，公斤）"],
["2855", "fisch", "KG", "Thunfisch Big Eye Saku semi (TK)", "Cá ngừ Big Eye Saku nhỏ (đông lạnh)", "Tuna Big Eye Saku semi (frozen)", "ทูน่า Big Eye Saku เล็ก (แช่แข็ง)", "大目金枪鱼柳 中份（冷冻）"],
["2851", "fisch", "KG", "Thunfisch Yellowfin Loins (TK)", "Cá ngừ Yellowfin phi lê (đông lạnh)", "Tuna Yellowfin loins (frozen)", "ทูน่าครีบเหลืองล็อยน์ (แช่แข็ง)", "黄鳍金枪鱼里脊（冷冻）"],
["1639", "fleisch", "KG", "Yakitori-Spieße 40g (Hähnchen, TK)", "Xiên gà Yakitori 40g (đông lạnh)", "Yakitori skewers 40g (chicken, frozen)", "ไก่เสียบไม้ยากิโทริ 40ก.", "鸡肉烤鸡串 40克（冷冻）"],
["80735", "verpackung", "Stueck", "Plastik Party Box M", "Hộp tiệc nhựa M", "Plastic party box M", "กล่องปาร์ตี้พลาสติก M", "塑料派对盒 M"],
["80736", "verpackung", "Stueck", "Plastik Party Box L", "Hộp tiệc nhựa L", "Plastic party box L", "กล่องปาร์ตี้พลาสติก L", "塑料派对盒 L"],
["80734", "verpackung", "Stueck", "Plastik Party Box S", "Hộp tiệc nhựa S", "Plastic party box S", "กล่องปาร์ตี้พลาสติก S", "塑料派对盒 S"],
["99338", "fisch", "KG", "Lachsfilet (SC, kg)", "Phi lê cá hồi (kg)", "Salmon fillet (kg)", "เนื้อปลาแซลมอน (กก.)", "三文鱼柳（公斤）"],
["4913", "fleisch", "Packung", "Gyoza Huhn & Gemüse (TK)", "Gyoza gà & rau (đông lạnh)", "Gyoza chicken & veg (frozen)", "เกี๊ยวซ่าไก่ผัก (แช่แข็ง)", "鸡肉蔬菜饺子（冷冻）"],
["80051-A", "sauce", "Packung", "Chilipaste", "Tương ớt", "Chili paste", "พริกแกง", "辣椒酱"],
["98118", "sauce", "Packung", "Sojasauce", "Nước tương", "Soy sauce", "ซีอิ๊ว", "酱油"],
["1649", "fleisch", "KG", "Chicken Katsu (TK, kg)", "Gà Katsu (đông lạnh)", "Chicken katsu (frozen)", "ไก่คัตสึ (แช่แข็ง)", "炸鸡排（冷冻，公斤）"],
["80161", "sauce", "Packung", "Golden Curry Currypaste (1kg)", "Cà ri Golden Curry (1kg)", "Golden curry paste (1kg)", "แกงกะหรี่ Golden Curry (1กก.)", "咖喱块 Golden Curry（1公斤）"],
["4804", "tk", "Packung", "Udonnudeln (TK)", "Mì Udon (đông lạnh)", "Udon noodles (frozen)", "เส้นอุด้ง (แช่แข็ง)", "乌冬面（冷冻）"],
["4675", "fleisch", "KGM", "Hähnchenbrust gegrillt 90-110g (TK)", "Ức gà nướng 90-110g (đông lạnh)", "Grilled chicken breast 90-110g (frozen)", "อกไก่ย่าง 90-110ก. (แช่แข็ง)", "烤鸡胸肉 90-110克（冷冻）"],
["307", "fisch", "", "Garnelen 41/50 Black Tiger (TK)", "Tôm Black Tiger 41/50 (đông lạnh)", "Shrimp Black Tiger 41/50 (frozen)", "กุ้งแบล็คไทเกอร์ 41/50 (แช่แข็ง)", "黑虎虾 41/50（冷冻）"],
["1648", "fleisch", "", "Chicken Tatsutaage (TK)", "Gà Tatsutaage (đông lạnh)", "Chicken tatsutaage (frozen)", "ไก่ทัตสึตะอาเกะ (แช่แข็ง)", "龙田炸鸡（冷冻）"],
["D7524333", "reinigung", "Stueck", "Papierhandtücher Z-Fold", "Khăn giấy gấp Z", "Paper towels Z-fold", "กระดาษเช็ดมือพับ Z", "Z形折叠纸巾"],
["100953747", "reinigung", "Flasche", "Suma QuickDes D4.12 Desinfektion", "Suma QuickDes D4.12 khử trùng", "Suma QuickDes D4.12 disinfectant", "Suma QuickDes D4.12 น้ำยาฆ่าเชื้อ", "Suma QuickDes D4.12 消毒液"],
["7511933", "reinigung", "Flasche", "Suma Light D1.2 Spülmittel", "Suma Light D1.2 nước rửa chén", "Suma Light D1.2 dish soap", "Suma Light D1.2 น้ำยาล้างจาน", "Suma Light D1.2 洗碗液"],
["7010025", "reinigung", "Flasche", "Suma Multi D2 Reiniger", "Suma Multi D2 chất tẩy rửa", "Suma Multi D2 cleaner", "Suma Multi D2 น้ำยาทำความสะอาด", "Suma Multi D2 清洁剂"],
["7516437", "reinigung", "Flasche", "Suma Cit D5.8 Entkalker", "Suma Cit D5.8 tẩy cặn vôi", "Suma Cit D5.8 descaler", "Suma Cit D5.8 น้ำยาขจัดคราบ", "Suma Cit D5.8 除垢剂"],
["7517445", "reinigung", "Stück", "Suma Lavette Green Tücher", "Khăn lau Suma Lavette Green", "Suma Lavette Green wipes", "ผ้าเช็ด Suma Lavette Green", "Suma Lavette Green 抹布"],
["100875238", "reinigung", "Flasche", "Soft Care Sensisept Handseife", "Soft Care Sensisept xà phòng tay", "Soft Care Sensisept hand soap", "Soft Care Sensisept สบู่ล้างมือ", "Soft Care Sensisept 洗手液"],
["7513050", "reinigung", "Flasche", "TASKI Sprint Glasreiniger", "TASKI Sprint lau kính", "TASKI Sprint glass cleaner", "TASKI Sprint น้ำยาเช็ดกระจก", "TASKI Sprint 玻璃清洁剂"],
["101103807", "reinigung", "Flasche", "Soft Care Des E H5 Desinfektion", "Soft Care Des E H5 khử trùng", "Soft Care Des E H5 disinfectant", "Soft Care Des E H5 ฆ่าเชื้อ", "Soft Care Des E H5 消毒液"],
["100959758", "reinigung", "Flasche", "SURE Antibac Handwaschmittel", "SURE Antibac rửa tay", "SURE Antibac hand wash", "SURE Antibac น้ำยาล้างมือ", "SURE Antibac 抗菌洗手液"],
["100953625", "reinigung", "Packung", "Soft Care Aquagard H72", "Soft Care Aquagard H72", "Soft Care Aquagard H72", "Soft Care Aquagard H72", "Soft Care Aquagard H72"],
["7010097", "reinigung", "Kanister", "Suma Lima L3 Spülmaschine (10l)", "Suma Lima L3 máy rửa chén (10l)", "Suma Lima L3 dishwasher (10l)", "Suma Lima L3 เครื่องล้างจาน (10ล.)", "Suma Lima L3 洗碗机用（10升）"],
["7010130", "reinigung", "Kanister", "Suma Rinse A5 Klarspüler (10l)", "Suma Rinse A5 nước làm bóng (10l)", "Suma Rinse A5 rinse aid (10l)", "Suma Rinse A5 น้ำยาช่วยล้าง (10ล.)", "Suma Rinse A5 亮碟剂（10升）"],
["100848994", "reinigung", "Packung", "Sun PF Spülmaschinensalz", "Sun PF muối máy rửa chén", "Sun PF dishwasher salt", "Sun PF เกลือเครื่องล้างจาน", "Sun PF 洗碗机盐"],
["100892014", "reinigung", "Flasche", "SURE Descaler Entkalker", "SURE Descaler tẩy cặn vôi", "SURE Descaler", "SURE Descaler น้ำยาขจัดคราบ", "SURE Descaler 除垢剂"],
["AF10000", "gemuese", "Stueck", "Avocados (Ready to Eat)", "Bơ (chín sẵn)", "Avocados (ready to eat)", "อะโวคาโด (พร้อมทาน)", "牛油果（即食）"],
["AF10020", "gemuese", "Schale", "Erdbeeren Schale 500g", "Dâu tây khay 500g", "Strawberries tray 500g", "สตรอว์เบอร์รี ถาด 500ก.", "草莓 盒装500克"],
["AF10001", "gemuese", "Stueck", "Salatgurken 400-500g", "Dưa leo 400-500g", "Cucumbers 400-500g", "แตงกวา 400-500ก.", "黄瓜 400-500克"],
["AF10003", "gemuese", "Stueck", "Paprika rot (lose)", "Ớt chuông đỏ", "Red bell pepper", "พริกหวานแดง", "红甜椒（散装）"],
["AF10007", "gemuese", "Kiste", "Rucola 100g Bund", "Rau Rucola bó 100g", "Rucola bunch 100g", "รูโคลา มัด 100ก.", "芝麻菜 束装100克"],
["AF10018", "gemuese", "Schale", "Rucola 100g Schale", "Rau Rucola khay 100g", "Rucola tray 100g", "รูโคลา ถาด 100ก.", "芝麻菜 盒装100克"],
["AF10010", "gemuese", "Bund", "Schnittlauch 100g Bund", "Hẹ tây bó 100g", "Chives bunch 100g", "ต้นหอมซอย มัด 100ก.", "细香葱 束装100克"],
["AF10006", "gemuese", "Stueck", "Mango (Ready to Eat)", "Xoài (chín sẵn)", "Mango (ready to eat)", "มะม่วง (พร้อมทาน)", "芒果（即食）"],
["AF10008", "gemuese", "Schale", "Dill (lose)", "Thì là", "Dill", "ผักชีลาว", "莳萝（散装）"],
["AF10005", "gemuese", "Stueck", "Eisbergsalat (lose)", "Xà lách Mỹ", "Iceberg lettuce", "ผักกาดแก้ว", "结球生菜（散装）"],
["AF10012", "gemuese", "Beutel", "Koriander 100g", "Ngò rí 100g", "Coriander 100g", "ผักชี 100ก.", "香菜 100克"],
["AF10011", "gemuese", "Beutel", "Minze 100g", "Bạc hà 100g", "Mint 100g", "สะระแหน่ 100ก.", "薄荷 100克"],
["AF10009", "gemuese", "Stueck", "Basilikum 40g", "Húng quế 40g", "Basil 40g", "โหระพา 40ก.", "罗勒 40克"],
["AF10046", "gemuese", "KG", "Zwiebeln rot 1kg", "Hành tím 1kg", "Red onions 1kg", "หอมแดง 1กก.", "红洋葱 1公斤"],
["AF10039", "gemuese", "KG", "Karotten 1kg", "Cà rốt 1kg", "Carrots 1kg", "แครอท 1กก.", "胡萝卜 1公斤"],
["AF10004", "gemuese", "Stueck", "Zitronen (Stück)", "Chanh vàng (quả)", "Lemons (piece)", "เลมอน (ลูก)", "柠檬（个）"],
["AF10056", "gemuese", "Packung", "Broccoli 500g", "Bông cải xanh 500g", "Broccoli 500g", "บร็อคโคลี 500ก.", "西兰花 500克"],
["AF10610", "gemuese", "Stueck", "Rotkohl 720ml Glas", "Bắp cải tím lọ 720ml", "Red cabbage jar 720ml", "กะหล่ำม่วงขวด 720มล.", "紫甘蓝 玻璃罐720毫升"],
["AF10216", "sonstige", "Packung", "Speisesalz 500g", "Muối ăn 500g", "Table salt 500g", "เกลือ 500ก.", "食盐 500克"],
["AF10217", "sonstige", "Stueck", "Exquisa Frischkäse 200g", "Phô mai Exquisa 200g", "Exquisa cream cheese 200g", "ครีมชีส Exquisa 200ก.", "Exquisa 奶油奶酪 200克"],
["AF11201", "sonstige", "Packung", "Rote Bete Saft 0,5l", "Nước củ dền 0,5l", "Beetroot juice 0.5l", "น้ำบีทรูท 0.5ล.", "甜菜根汁 0.5升"],
["AF10201", "sonstige", "Flasche", "Rapsöl 1l", "Dầu cải 1l", "Rapeseed oil 1l", "น้ำมันคาโนลา 1ล.", "菜籽油 1升"],
["AF12001", "fisch", "Stück", "Thunfisch im eigenen Saft 500g", "Cá ngừ ngâm 500g", "Tuna in own juice 500g", "ทูน่าในน้ำ 500ก.", "原汁金枪鱼罐头 500克"],
["AF10701", "sauce", "Flasche", "Sriracha Chilisauce 0,73l", "Tương ớt Sriracha 0,73l", "Sriracha chili sauce 0.73l", "ซอสศรีราชา 0.73ล.", "是拉差辣椒酱 0.73升"],
["AF10710", "sauce", "Flasche", "Okonomi Sauce 1,8l", "Sốt Okonomi 1,8l", "Okonomi sauce 1.8l", "ซอสโอโคโนมิ 1.8ล.", "御好烧酱 1.8升"],
["AF10705", "sauce", "Kanister", "Teriyaki Sauce 2,2l", "Sốt Teriyaki 2,2l", "Teriyaki sauce 2.2l", "ซอสเทอริยากิ 2.2ล.", "照烧汁 2.2升"],
["AF10104", "hygiene", "Packung", "Nitril-Handschuhe blau S", "Găng nitril xanh size S", "Nitrile gloves blue S", "ถุงมือไนไตรล์ฟ้า S", "蓝色丁腈手套 S"],
["AF10106", "hygiene", "Packung", "Nitril-Handschuhe blau L", "Găng nitril xanh size L", "Nitrile gloves blue L", "ถุงมือไนไตรล์ฟ้า L", "蓝色丁腈手套 L"],
["AF10105", "hygiene", "Packung", "Nitril-Handschuhe blau M", "Găng nitril xanh size M", "Nitrile gloves blue M", "ถุงมือไนไตรล์ฟ้า M", "蓝色丁腈手套 M"],
["AF10107", "hygiene", "Packung", "Nitril-Handschuhe blau XL", "Găng nitril xanh size XL", "Nitrile gloves blue XL", "ถุงมือไนไตรล์ฟ้า XL", "蓝色丁腈手套 XL"],
["AF10100", "hygiene", "Packung", "TPE-Handschuhe schwarz S", "Găng TPE đen size S", "TPE gloves black S", "ถุงมือ TPE ดำ S", "黑色TPE手套 S"],
["AF10101", "hygiene", "Packung", "TPE-Handschuhe schwarz M", "Găng TPE đen size M", "TPE gloves black M", "ถุงมือ TPE ดำ M", "黑色TPE手套 M"],
["AF10102", "hygiene", "Packung", "TPE-Handschuhe schwarz L", "Găng TPE đen size L", "TPE gloves black L", "ถุงมือ TPE ดำ L", "黑色TPE手套 L"],
["AF10103", "hygiene", "Packung", "TPE-Handschuhe schwarz XL", "Găng TPE đen size XL", "TPE gloves black XL", "ถุงมือ TPE ดำ XL", "黑色TPE手套 XL"],
["AF11100", "verpackung", "Packung", "Verkaufsetiketten Circle (10 Rollen)", "Nhãn bán hàng Circle (10 cuộn)", "Sales labels Circle (10 rolls)", "ฉลากขาย Circle (10 ม้วน)", "Circle 销售标签（10卷）"],
["AF10108", "verpackung", "Stück", "Küchenrolle 3-lagig (4er)", "Khăn giấy bếp 3 lớp (4 cuộn)", "Kitchen roll 3-ply (4-pack)", "กระดาษทิชชู่ครัว 3 ชั้น (4 ม้วน)", "三层厨房纸巾（4卷装）"],
["AF10109", "verpackung", "Stück", "Frischhaltefolie 45cm", "Màng bọc thực phẩm 45cm", "Cling film 45cm", "ฟิล์มถนอมอาหาร 45ซม.", "保鲜膜 45cm"],
["AF10112", "verpackung", "Stück", "Müllbeutel 120l blau", "Túi rác 120l xanh", "Garbage bags 120l blue", "ถุงขยะ 120ล. ฟ้า", "蓝色垃圾袋 120升"],
["AF10318", "verpackung", "Stück", "Spritzbeutel 128", "Túi bắt kem 128", "Piping bags 128", "ถุงบีบ 128", "裱花袋 128"],
["AF10320", "hygiene", "Stück", "Flüssiggas-Kartuschen 227g (4er)", "Bình gas mini 227g (4 cái)", "Gas cartridges 227g (4-pack)", "แก๊สกระป๋อง 227ก. (4 อัน)", "液化气瓶 227克（4个装）"],
["AF10321", "hygiene", "Stück", "Flambierbrenner mit Kartusche", "Đèn khò + bình gas", "Blowtorch with cartridge", "หัวพ่นไฟพร้อมแก๊ส", "喷枪（含气瓶）"],
["AF10110", "hygiene", "Stück", "Handdesinfektion Spray 0,5l", "Xịt sát khuẩn tay 0,5l", "Hand sanitizer spray 0.5l", "สเปรย์ล้างมือ 0.5ล.", "免洗手部消毒喷雾 0.5升"],
["AF10204", "sauce", "Stück", "Essig 5% Säure 5l", "Giấm 5% 5l", "Vinegar 5% 5l", "น้ำส้มสายชู 5% 5ล.", "食醋 5%酸度 5升"],
["AF10504", "reis", "Stück", "Kokosraspeln 200g", "Dừa nạo 200g", "Coconut flakes 200g", "มะพร้าวขูด 200ก.", "椰丝 200克"],
["AF10505", "dessert", "Stück", "Lotus Biscoff Kekse 200g", "Bánh quy Lotus Biscoff 200g", "Lotus Biscoff biscuits 200g", "คุกกี้ Lotus Biscoff 200ก.", "Lotus Biscoff 饼干 200克"],
["AF10506", "dessert", "Stück", "Vanille-Extrakt Ruf 77g", "Tinh chất vani Ruf 77g", "Vanilla extract Ruf 77g", "กลิ่นวานิลลา Ruf 77ก.", "Ruf 香草精 77克"],
["AF10508", "dessert", "Stück", "Gezuckerte Kondensmilch 150g", "Sữa đặc 150g", "Sweetened condensed milk 150g", "นมข้นหวาน 150ก.", "加糖炼乳 150克"],
["AF10507", "dessert", "Stück", "Puderzucker 250g", "Đường bột 250g", "Powdered sugar 250g", "น้ำตาลไอซิ่ง 250ก.", "糖粉 250克"],
["AF11117", "verpackung", "Rolle", "Dekoetikett \"Aktion\" 30mm", "Nhãn \"Aktion\" 30mm", "Deco label \"Aktion\" 30mm", "ฉลาก \"Aktion\" 30มม.", "装饰标签「促销」30mm"],
["AF11120", "verpackung", "Rolle", "Dekoetikett \"Neu\" 30mm", "Nhãn \"Neu\" (mới) 30mm", "Deco label \"Neu\" 30mm", "ฉลาก \"Neu\" 30มม.", "装饰标签「新品」30mm"],
["AF11118", "verpackung", "Rolle", "Dekoetikett \"Protein\" 30mm", "Nhãn \"Protein\" 30mm", "Deco label \"Protein\" 30mm", "ฉลาก \"Protein\" 30มม.", "装饰标签「蛋白质」30mm"],
["AF11119", "verpackung", "Rolle", "Dekoetikett \"Temperatur\" 30mm", "Nhãn \"Temperatur\" 30mm", "Deco label \"Temperatur\" 30mm", "ฉลาก \"Temperatur\" 30มม.", "装饰标签「温度」30mm"],
["AF11121", "verpackung", "Rolle", "Dekoetikett \"Favoriten\" 30mm", "Nhãn \"Favoriten\" 30mm", "Deco label \"Favoriten\" 30mm", "ฉลาก \"Favoriten\" 30มม.", "装饰标签「人气推荐」30mm"],
["AF11111", "verpackung", "Rolle", "Schmucketikett \"Fisch & Meer\"", "Nhãn trang trí \"Cá & Biển\"", "Deco label \"Fish & Sea\"", "ฉลาก \"ปลาและทะเล\"", "装饰标签「鱼类与海鲜」"],
["AF11112", "verpackung", "Rolle", "Schmucketikett \"Veggie\"", "Nhãn trang trí \"Chay\"", "Deco label \"Veggie\"", "ฉลาก \"เจ\"", "装饰标签「素食」"],
["AF11113", "fisch", "Rolle", "Schmucketikett \"Lachs\"", "Nhãn trang trí \"Cá hồi\"", "Deco label \"Salmon\"", "ฉลาก \"แซลมอน\"", "装饰标签「三文鱼」"],
["AF11114", "verpackung", "Rolle", "Schmucketikett \"Hühnchen\"", "Nhãn trang trí \"Gà\"", "Deco label \"Chicken\"", "ฉลาก \"ไก่\"", "装饰标签「鸡肉」"],
["AF11115", "fisch", "Rolle", "Schmucketikett \"Thunfisch\"", "Nhãn trang trí \"Cá ngừ\"", "Deco label \"Tuna\"", "ฉลาก \"ทูน่า\"", "装饰标签「金枪鱼」"],
["AF11116", "verpackung", "Rolle", "Schmucketikett \"Dessert\"", "Nhãn trang trí \"Tráng miệng\"", "Deco label \"Dessert\"", "ฉลาก \"ของหวาน\"", "装饰标签「甜点」"],
["AF11147", "verpackung", "", "Verkaufsetiketten endlos Termo", "Nhãn bán hàng cuộn (nhiệt)", "Sales labels thermal roll", "ฉลากขายม้วนความร้อน", "热敏连续销售标签"],
["AF10400", "sauce", "Stueck", "Saucenbecher 30ml (50 Stk)", "Cốc đựng sốt 30ml (50 cái)", "Sauce cups 30ml (50 pcs)", "ถ้วยซอส 30มล. (50 ใบ)", "酱料杯 30毫升（50个装）"],
["AF10465", "verpackung", "Stück", "Sushi Box S (540 Stk)", "Hộp sushi S (540 cái)", "Sushi box S (540 pcs)", "กล่องซูชิ S (540 ใบ)", "寿司盒 S（540个装）"],
["AF10471", "verpackung", "Stück", "Sushi Box Slim (280 Stk)", "Hộp sushi Slim (280 cái)", "Sushi box slim (280 pcs)", "กล่องซูชิ Slim (280 ใบ)", "寿司盒 细长款（280个装）"],
["AF10474", "tk", "", "Sushi Box Mochi (630 Stk)", "Hộp sushi Mochi (630 cái)", "Sushi box mochi (630 pcs)", "กล่องซูชิ Mochi (630 ใบ)", "大福寿司盒（630个装）"],
["AF 10480", "verpackung", "Stück", "Sushi Box L (220 Stk)", "Hộp sushi L (220 cái)", "Sushi box L (220 pcs)", "กล่องซูชิ L (220 ใบ)", "寿司盒 L（220个装）"],
["AF10457", "verpackung", "Stueck", "Sushi Box XL Papier (160 Stk)", "Hộp sushi XL giấy (160 cái)", "Sushi box XL paper (160 pcs)", "กล่องซูชิ XL กระดาษ (160 ใบ)", "寿司盒 XL 纸质（160个装）"],
["AF10472", "verpackung", "Stück", "Sushi Box Family 2 (140 Stk)", "Hộp sushi Family 2 (140 cái)", "Sushi box family 2 (140 pcs)", "กล่องซูชิ Family 2 (140 ใบ)", "寿司盒 家庭装2号（140个装）"],
["AF12206", "verpackung", "Stück", "Poke Bowl 750ml (200 Stk)", "Tô Poke 750ml (200 cái)", "Poke bowl 750ml (200 pcs)", "ชามโปเก้ 750มล. (200 ใบ)", "缤纷碗餐盒 750毫升（200个装）"],
["AF10491", "verpackung", "", "Sushi Box Party rund L + Deckel", "Hộp sushi tiệc tròn L + nắp", "Sushi party box round L + lid", "กล่องซูชิปาร์ตี้กลม L + ฝา", "圆形派对寿司盒 L + 盖子"],
["AF10499", "verpackung", "Stück", "Papiertragetaschen groß", "Túi giấy lớn", "Paper bags large", "ถุงกระดาษใหญ่", "大号纸袋"],
["AF12275", "verpackung", "", "Papiertragetasche flach 32×22×24", "Túi giấy quai dẹt 32×22×24", "Paper bag flat handle 32×22×24", "ถุงกระดาษหูแบน 32×22×24", "扁平纸袋 32×22×24"],
["AF10489", "verpackung", "Stück", "Sushi Box Slim (400 Stk)", "Hộp sushi Slim (400 cái)", "Sushi box slim (400 pcs)", "กล่องซูชิ Slim (400 ใบ)", "寿司盒 细长款（400个装）"],
["AF10450", "verpackung", "Stück", "Sushi Box S (400 Stk)", "Hộp sushi S (400 cái)", "Sushi box S (400 pcs)", "กล่องซูชิ S (400 ใบ)", "寿司盒 S（400个装）"],
["AF10488", "verpackung", "Stück", "Sushi Box L (400 Stk)", "Hộp sushi L (400 cái)", "Sushi box L (400 pcs)", "กล่องซูชิ L (400 ใบ)", "寿司盒 L（400个装）"],
["AF12205", "reis", "Packung", "Kokosmilch Aroy-D 1l", "Nước cốt dừa Aroy-D 1l", "Coconut milk Aroy-D 1l", "กะทิ Aroy-D 1ล.", "Aroy-D 椰浆 1升"],
["AF10322", "verpackung", "", "Gefrierbeutel 1l (20 Stk)", "Túi đông lạnh 1l (20 cái)", "Freezer bags 1l (20 pcs)", "ถุงแช่แข็ง 1ล. (20 ใบ)", "冷冻袋 1升（20个装）"],
["AF12255", "sauce", "", "Kimchi Original 1kg", "Kimchi nguyên bản 1kg", "Kimchi original 1kg", "กิมจิ 1กก.", "原味泡菜 1公斤"],
["AF12276", "sonstige", "", "Vegan Brioche Sandwich 375g", "Bánh mì Brioche chay 375g", "Vegan brioche sandwich 375g", "ขนมปังบรียอชเจ 375ก.", "素食奶油面包 375克"],
["AF12277", "sauce", "", "Senf mittelscharf 200g", "Mù tạt vàng vừa cay 200g", "Mustard medium 200g", "มัสตาร์ด 200ก.", "中辣芥末酱 200克"],
["AF12286", "verpackung", "Stück", "Donutverpackung Grab & Go (100 Stk)", "Hộp donut Grab & Go (100 cái)", "Donut packaging Grab & Go (100 pcs)", "กล่องโดนัท Grab & Go (100 ใบ)", "甜甜圈外带包装（100个装）"],
["AF12080", "sauce", "", "Yakisoba Sauce 1,8l", "Sốt Yakisoba 1,8l", "Yakisoba sauce 1.8l", "ซอสยากิโซบะ 1.8ล.", "炒面酱 1.8升"],
["AF12354", "dessert", "Stück", "Jin Ramen Spicy (Otoki)", "Mì Jin Ramen cay", "Jin Ramen spicy", "จินราเมงเผ็ด", "辛拉面 辣味"],
["AF12355", "dessert", "Stück", "Jin Ramen Mild (Otoki)", "Mì Jin Ramen nhẹ", "Jin Ramen mild", "จินราเมงอ่อน", "辛拉面 温和"],
["AF12399", "dessert", "Packung", "Tortilla Chips mit Salz 300g", "Bánh Tortilla muối 300g", "Tortilla chips salted 300g", "ทอร์ทิญ่าเค็ม 300ก.", "咸味玉米片 300克"],
["AF12356", "tk", "Stück", "Kaludon Kimchi (Korean Street)", "Kimchi Kaludon", "Kaludon kimchi", "กิมจิ Kaludon", "Kaludon 泡菜"],
["AF12357", "sonstige", "Stück", "Crispy Seaweed Gochujang", "Rong biển giòn Gochujang", "Crispy seaweed gochujang", "สาหร่ายกรอบโกชูจัง", "辣酱脆海苔"],
["AF12358", "sauce", "Stück", "Teriyaki Chips (Koikeya)", "Snack Teriyaki", "Teriyaki chips", "ขนมเทอริยากิ", "照烧薯片"],
["AF12359", "dessert", "Stück", "Teokbokki Spicy (Haitai)", "Bánh gạo cay Teokbokki", "Teokbokki spicy", "ต๊อกบกกีเผ็ด", "辣炒年糕"],
["AF10054", "gemuese", "Stück", "Limetten (Stück)", "Chanh xanh (quả)", "Limes (piece)", "มะนาว (ลูก)", "青柠（个）"],
["AF12027", "sauce", "Flasche", "Shoda Sojasauce 1L", "Nước tương Shoda 1L", "Shoda soy sauce 1L", "ซีอิ๊วโชดะ 1ล.", "Shoda 酱油 1升"],
["AF12386", "verpackung", "Stück", "Sushi Push-Up mit Logo", "Hộp Push-Up có logo", "Sushi push-up with logo", "ซูชิพุชอัพมีโลโก้", "印logo推推寿司杯"],
["AF12396", "reis", "KG", "Japonica Reis (Zensho) 10kg", "Gạo Japonica (Zensho) 10kg", "Japonica rice (Zensho) 10kg", "ข้าวจาโปนิก้า 10กก.", "粳米（Zensho）10公斤"],
["AF12447", "sauce", "Packung", "Kimchi Original + Verpackung 1kg", "Kimchi nguyên bản + bao bì 1kg", "Kimchi original + packaging 1kg", "กิมจิ + บรรจุภัณฑ์ 1กก.", "原味泡菜+包装 1公斤"]
];
window.INVENTUR_CATS=[["fisch", "🐟 Fisch & Meeresfrüchte", "🐟 Cá & Hải sản", "🐟 Fish & Seafood", "🐟 ปลาและอาหารทะเล", "🐟 鱼类与海鲜"], ["fleisch", "🍗 Fleisch & Geflügel", "🍗 Thịt & Gia cầm", "🍗 Meat & Poultry", "🍗 เนื้อสัตว์", "🍗 肉类与禽类"], ["tk", "❄️ Tiefkühl", "❄️ Đông lạnh", "❄️ Frozen", "❄️ แช่แข็ง", "❄️ 冷冻食品"], ["gemuese", "🥬 Gemüse & Obst", "🥬 Rau & Trái cây", "🥬 Vegetables & Fruit", "🥬 ผักและผลไม้", "🥬 蔬菜水果"], ["sauce", "🍶 Saucen & Würze", "🍶 Nước sốt & Gia vị", "🍶 Sauces & Seasoning", "🍶 ซอสและเครื่องปรุง", "🍶 酱料调味"], ["reis", "🍚 Reis & Trocken", "🍚 Gạo & Đồ khô", "🍚 Rice & Dry goods", "🍚 ข้าวและของแห้ง", "🍚 米类与干货"], ["dessert", "🍡 Dessert & Snack", "🍡 Tráng miệng & Snack", "🍡 Dessert & Snacks", "🍡 ของหวานและขนม", "🍡 甜点零食"], ["verpackung", "📦 Verpackung & Etiketten", "📦 Bao bì & Nhãn", "📦 Packaging & Labels", "📦 บรรจุภัณฑ์", "📦 包装与标签"], ["hygiene", "🧤 Hygiene", "🧤 Vệ sinh tiêu hao", "🧤 Hygiene", "🧤 สุขอนามัย", "🧤 卫生用品"], ["reinigung", "🧴 Reinigung", "🧴 Hóa chất tẩy rửa", "🧴 Cleaning", "🧴 น้ำยาทำความสะอาด", "🧴 清洁用品"], ["sonstige", "❓ Sonstige", "❓ Khác", "❓ Other", "❓ อื่นๆ", "❓ 其他"]];
window.INVENTUR_VERSION='2025-06';
